export const CHAT_CONSTANTS = {
  RECOMMENDED_SECTION_SPACING: 2,
  CHIP_PADDING_HORIZONTAL: 22,
  CHIP_PADDING_VERTICAL: 10,
  MESSAGE_LIST_PADDING: 16,
  INPUT_PADDING: 12,

  RECOMMENDED_LABEL_FONT_SIZE: 10,
  CHIP_FONT_SIZE: 12,
  MESSAGE_FONT_SIZE: 14,
  INPUT_PLACEHOLDER_FONT_SIZE: 12,

  CHIP_LETTER_SPACING: -0.24,

  LABEL_OPACITY: 0.5,
  PLACEHOLDER_OPACITY: 0.5,

  RECOMMENDED_LABEL: '추천 질문',
  INPUT_PLACEHOLDER: '텍스트를 입력해주세요.',
  DEFAULT_RESPONSE: '기본 답변',

  INITIAL_GREETING_MESSAGES: [
    '안녕 만나서 반가워!',
    '오늘은 어떤 것을 도와줄까?',
  ],

  MAX_MESSAGE_LENGTH: 500,
} as const;
