import { MapMarker } from './mapModel';

export const mockPlacesWithCoordinates: MapMarker[] = [
  {
    id: '1',
    name: '울산 문화의 거리',
    address: '울산광역시 중구 성남동 329-5',
    latitude: 35.5684,
    longitude: 129.3116,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 12,
    rating: 4,
  },
  {
    id: '2',
    name: '서울 종로 전통주 거리',
    address: '서울특별시 종로구 종로3가 112',
    latitude: 37.5709,
    longitude: 126.9920,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 8,
    rating: 3,
  },
  {
    id: '3',
    name: '전주 한옥마을',
    address: '전라북도 전주시 완산구 기린대로 99',
    latitude: 35.8162,
    longitude: 127.1530,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 15,
    rating: 5,
  },
  {
    id: '4',
    name: '경주 교동법주마을',
    address: '경상북도 경주시 교동 69',
    latitude: 35.8562,
    longitude: 129.2088,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 10,
    rating: 4,
  },
  {
    id: '5',
    name: '부산 광안리 해변',
    address: '부산광역시 수영구 광안해변로 219',
    latitude: 35.1532,
    longitude: 129.1183,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 20,
    rating: 5,
  },
  {
    id: '6',
    name: '대전 으능정이 거리',
    address: '대전광역시 중구 은행동 145',
    latitude: 36.3272,
    longitude: 127.4281,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 7,
    rating: 3,
  },
  {
    id: '7',
    name: '강릉 경포대',
    address: '강원도 강릉시 경포로 365',
    latitude: 37.7956,
    longitude: 128.8961,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 13,
    rating: 4,
  },
  {
    id: '8',
    name: '인천 차이나타운',
    address: '인천광역시 중구 차이나타운로 12',
    latitude: 37.4756,
    longitude: 126.6173,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 21,
    rating: 3,
  },
  {
    id: '9',
    name: '서울 이태원 경리단길',
    address: '서울특별시 용산구 이태원동 127-1',
    latitude: 37.5344,
    longitude: 126.9944,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 7,
    rating: 5,
  },
  {
    id: '10',
    name: '서울 홍대 걷고싶은거리',
    address: '서울특별시 마포구 양화로 160',
    latitude: 37.5563,
    longitude: 126.9234,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 12,
    rating: 3,
  },
  {
    id: '11',
    name: '서울 강남 신사동 가로수길',
    address: '서울특별시 강남구 신사동 549-8',
    latitude: 37.5196,
    longitude: 127.0228,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 23,
    rating: 5,
  },
  {
    id: '12',
    name: '서울 명동 거리',
    address: '서울특별시 중구 명동2가 25-1',
    latitude: 37.5635,
    longitude: 126.9849,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 12,
    rating: 3,
  },
  {
    id: '13',
    name: '서울 삼청동 한옥거리',
    address: '서울특별시 종로구 삼청로 48',
    latitude: 37.5836,
    longitude: 126.9821,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 6,
    rating: 3,
  },
  {
    id: '14',
    name: '서울 서촌 통인시장',
    address: '서울특별시 종로구 자하문로15길 18',
    latitude: 37.5798,
    longitude: 126.9691,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 19,
    rating: 4,
  },
  {
    id: '15',
    name: '서울 성수동 카페거리',
    address: '서울특별시 성동구 연무장길 74',
    latitude: 37.5447,
    longitude: 127.0557,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 17,
    rating: 5,
  },
  {
    id: '16',
    name: '서울 망원동 경의선숲길',
    address: '서울특별시 마포구 망원동 410-1',
    latitude: 37.5561,
    longitude: 126.9036,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 14,
    rating: 5,
  },
  {
    id: '17',
    name: '서울 한남동 이태원로',
    address: '서울특별시 용산구 한남동 683-205',
    latitude: 37.5349,
    longitude: 127.0025,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 12,
    rating: 4,
  },
  {
    id: '18',
    name: '서울 광화문 광장',
    address: '서울특별시 종로구 세종대로 172',
    latitude: 37.5720,
    longitude: 126.9769,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 21,
    rating: 5,
  },
  {
    id: '19',
    name: '서울 북촌 한옥마을',
    address: '서울특별시 종로구 계동길 37',
    latitude: 37.5820,
    longitude: 126.9851,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 10,
    rating: 4,
  },
  {
    id: '20',
    name: '서울 연남동 먹자골목',
    address: '서울특별시 마포구 동교로 203',
    latitude: 37.5637,
    longitude: 126.9247,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 18,
    rating: 5,
  },
  {
    id: '21',
    name: '서울 건대 로데오거리',
    address: '서울특별시 광진구 능동로 110',
    latitude: 37.5403,
    longitude: 127.0695,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 14,
    rating: 5,
  },
  {
    id: '22',
    name: '서울 신촌 연세로',
    address: '서울특별시 서대문구 신촌동 134',
    latitude: 37.5585,
    longitude: 126.9380,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 17,
    rating: 5,
  },
  {
    id: '23',
    name: '서울 압구정 로데오거리',
    address: '서울특별시 강남구 압구정로 80길 38',
    latitude: 37.5274,
    longitude: 127.0380,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 23,
    rating: 4,
  },
  {
    id: '24',
    name: '서울 청담동 명품거리',
    address: '서울특별시 강남구 청담동 128-1',
    latitude: 37.5237,
    longitude: 127.0474,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 21,
    rating: 3,
  },
  {
    id: '25',
    name: '서울 여의도 한강공원',
    address: '서울특별시 영등포구 여의동로 330',
    latitude: 37.5285,
    longitude: 126.9348,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 9,
    rating: 3,
  },
  {
    id: '26',
    name: '서울 용리단길',
    address: '서울특별시 용산구 신흥로 45',
    latitude: 37.5301,
    longitude: 126.9686,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 8,
    rating: 3,
  },
  {
    id: '27',
    name: '서울 을지로 힙지로',
    address: '서울특별시 중구 을지로 148',
    latitude: 37.5665,
    longitude: 126.9918,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 8,
    rating: 5,
  },
  {
    id: '28',
    name: '서울 동대문 DDP',
    address: '서울특별시 중구 을지로 281',
    latitude: 37.5675,
    longitude: 127.0090,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 12,
    rating: 3,
  },
  {
    id: '29',
    name: '서울 혜화동 대학로',
    address: '서울특별시 종로구 대학로 116',
    latitude: 37.5821,
    longitude: 127.0012,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 7,
    rating: 5,
  },
  {
    id: '30',
    name: '서울 성북동 한옥거리',
    address: '서울특별시 성북구 성북로 96',
    latitude: 37.5932,
    longitude: 126.9943,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 11,
    rating: 3,
  },
  {
    id: '31',
    name: '서울 상수동 카페거리',
    address: '서울특별시 마포구 와우산로 29길 18',
    latitude: 37.5481,
    longitude: 126.9230,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 13,
    rating: 4,
  },
  {
    id: '32',
    name: '서울 서래마을',
    address: '서울특별시 서초구 서래로 29',
    latitude: 37.4884,
    longitude: 127.0031,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 18,
    rating: 5,
  },
  {
    id: '33',
    name: '서울 한강진역 거리',
    address: '서울특별시 용산구 이태원로 294',
    latitude: 37.5348,
    longitude: 126.9923,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 19,
    rating: 3,
  },
  {
    id: '34',
    name: '서울 송리단길',
    address: '서울특별시 강남구 석촌호수로 262',
    latitude: 37.5057,
    longitude: 127.1046,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 10,
    rating: 4,
  },
  {
    id: '35',
    name: '서울 경복궁 서촌',
    address: '서울특별시 종로구 통인동 10',
    latitude: 37.5782,
    longitude: 126.9697,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 6,
    rating: 5,
  },
  {
    id: '36',
    name: '서울 한남 더힐',
    address: '서울특별시 용산구 대사관로 35',
    latitude: 37.5331,
    longitude: 127.0024,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 5,
    rating: 4,
  },
  {
    id: '37',
    name: '서울 마장동 먹자골목',
    address: '서울특별시 성동구 마장로 140',
    latitude: 37.5660,
    longitude: 127.0380,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 22,
    rating: 3,
  },
  {
    id: '38',
    name: '서울 익선동 한옥거리',
    address: '서울특별시 종로구 돈화문로11다길 24',
    latitude: 37.5718,
    longitude: 126.9855,
    imageUrl: require('@/assets/images/example_image.png'),
    feedCount: 8,
    rating: 5,
  },
];
